In [2]:
import torch
import torch.nn.functional as F

/root/miniconda3/envs/SimKGC/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
ent = torch.load('entities.pt')

In [4]:
batch = torch.load('batch.pt')

In [13]:
tail = batch[:,2,:]

In [9]:
ent.shape

torch.Size([40943, 768])

In [15]:
tail[0]

tensor([-3.5531e-01,  5.8244e-01,  3.6436e-01, -3.5334e-02,  1.9858e-01,
         4.2213e-02,  2.6173e-01, -1.6826e-01, -2.7101e-01,  6.9702e-02,
        -1.3384e-01, -2.0730e-01, -5.6426e-01,  6.3620e-01,  1.4630e-01,
         1.1918e+00,  2.7937e-01, -3.4571e-01, -1.8044e-01,  3.8292e-01,
         6.7630e-01,  7.6282e-01,  3.1501e-01,  5.6483e-01, -3.1746e-01,
         2.2878e-01,  5.0415e-01, -1.2934e-01, -3.7017e-01, -3.6587e-01,
         5.6949e-02, -1.9953e-01, -6.9347e-02,  3.7914e-04,  1.4319e-01,
         2.7755e-01, -1.5659e-01, -1.7082e-01,  4.5403e-01,  8.0928e-02,
        -3.8191e-01, -8.3563e-01, -9.6054e-02, -1.3413e-01,  2.5228e-02,
        -3.9417e-01, -5.3205e-02,  6.6062e-01, -2.6445e-01, -3.0142e-01,
        -6.0378e-01, -1.1268e-01,  4.5571e-01, -3.9700e-01,  2.1178e-01,
         3.4968e-01,  6.9649e-02, -4.2132e-01,  3.2752e-01,  1.3629e-01,
        -3.4570e-01, -4.0819e-01, -2.2138e-01,  4.3596e-01, -1.8537e-01,
        -1.8794e-01, -3.0045e-01,  3.8738e-01, -4.8

In [17]:
ent[0]

tensor([ 2.1636e-02, -2.4291e-01,  6.1822e-01, -1.4039e-01,  7.1793e-01,
        -1.8606e-01, -4.1962e-01,  1.1446e-01, -2.6075e-01, -3.0857e-01,
        -2.1173e-01,  3.9186e-01, -2.4672e-01,  1.2387e-01,  8.1900e-02,
         9.5608e-01, -2.0760e-02,  2.1633e-01, -2.3774e-01,  2.5686e-02,
         5.8017e-01,  4.2286e-02,  6.5961e-02,  5.2090e-01,  2.4589e-01,
        -1.6251e-01,  3.7675e-01, -1.8855e-01, -4.5066e-01, -2.3413e-01,
         9.3360e-02, -4.4936e-01,  1.3360e-01,  1.7874e-01,  1.7113e-01,
         1.7248e-01,  1.5739e-01, -2.7982e-01,  1.2994e-01, -1.0548e-01,
        -5.2103e-01, -2.8075e-01, -9.7135e-02,  2.2138e-01,  1.3167e-01,
        -3.7026e-01,  9.6422e-02,  2.8901e-02,  5.0582e-01, -3.6593e-01,
        -4.1479e-01,  3.9603e-01,  3.3447e-01, -3.4319e-01,  6.4282e-01,
         4.5512e-01, -2.0756e-01, -3.7665e-01, -3.0668e-01, -1.8619e-01,
        -3.3282e-01, -2.3714e-01,  8.6120e-02, -1.8940e-01, -2.6400e-01,
        -8.7783e-02, -1.7289e-01,  3.1034e-01, -4.6

In [22]:
res = torch.isin(tail, ent)

In [27]:
torch.all(res, 1).nonzero()

tensor([], size=(0, 1), dtype=torch.int64)

In [24]:
res

tensor([[ True, False, False,  ..., False, False,  True],
        [False, False,  True,  ..., False,  True, False],
        [False, False,  True,  ...,  True,  True, False],
        ...,
        [False, False, False,  ..., False,  True, False],
        [False, False,  True,  ..., False,  True, False],
        [False, False, False,  ..., False, False, False]])

In [19]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([1,2,3,4])

In [20]:
torch.isin(a, b)

tensor([True, True, True, True])