In [1]:
import torch
import torch.nn.functional as F

/root/miniconda3/envs/SimKGC/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
torch.tensor([]).shape[0]

0

In [2]:
a = torch.rand(4, 7)

In [3]:
b = torch.rand(4, 7)

In [5]:
c = torch.norm(a - b, dim=1, p=1)

In [7]:
F.logsigmoid(c)

tensor([[-0.1770, -0.1005, -0.0624, -0.0631]])

In [29]:
def score_fn(true_tail, pred_tail):
    score = torch.abs(pred_tail - true_tail)
    score = torch.norm(score, p=1, dim=(1,2))
    score = F.logsigmoid(score).squeeze(dim=0)
    # return score
    return score

In [25]:
sim = torch.nn.CosineSimilarity(dim=0, eps=1e-6)

In [31]:
a = torch.rand(5, 2, 3)

In [32]:
a

tensor([[[0.6317, 0.4259, 0.6527],
         [0.3254, 0.9419, 0.5991]],

        [[0.9810, 0.7444, 0.1362],
         [0.4513, 0.6190, 0.8160]],

        [[0.6404, 0.1710, 0.2194],
         [0.3779, 0.8172, 0.7076]],

        [[0.9740, 0.7682, 0.9840],
         [0.5451, 0.0174, 0.8446]],

        [[0.1890, 0.4078, 0.9688],
         [0.1833, 0.3058, 0.9870]]])

In [35]:
torch.mean(a, dim=1)

tensor([[0.4786, 0.6839, 0.6259],
        [0.7162, 0.6817, 0.4761],
        [0.5092, 0.4941, 0.4635],
        [0.7595, 0.3928, 0.9143],
        [0.1862, 0.3568, 0.9779]])

In [28]:
score = score_fn(a, b)
score

NameError: name 'score_fn' is not defined

In [29]:
def all_axis(tensor):
    new_tensor = []
    for i in tensor:
        new_tensor.append(torch.all(i))
    new_tensor = torch.tensor(new_tensor)
    return new_tensor

In [30]:
all_axis(a==b)

tensor([True, True, True, True, True])